language: ruby
cache: bundler
 
before_script: 
  - gem install bundler:2.0.1
  - bundle install
  - bundle update
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
script: 'bundle exec cucumber features/*'
 
branches:
  only:
    - master