sudo: false
language: ruby
cache: bundler

addons:
  apt:
    packages:
      - google-chrome-stable


before_script: 
  - gem install bundler:2.0.1
  - bundle install
  - bundle update
  - sudo apt-get install libnss3
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
script: 'bundle exec cucumber features/*'
 
branches:
  only:
    - master

    