sudo: required
dist: trusty
language: ruby
cache: bundler

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_script: 
  - gem install bundler:2.0.1
  - bundle install
  - bundle update
  - sudo apt-get install libnss3
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 'bundle exec cucumber features/*'
    